Repository elastic/synthetics-recorder, pull requests merged in 2022-04, with the labels that each got.

#171 feat: switch `Steps` data structure from nested array to map
  e2e/tests/navigation.test.ts
  electron/execution.js
  package-lock.json
  package.json
  src/App.tsx
  src/common/shared.test.ts
  src/common/shared.ts
  src/common/types.ts
  src/components/ActionDetail/ActionDetail.tsx
  src/components/Assertion/Assertion.tsx
  src/components/ExportScriptFlyout/Flyout.tsx
  src/components/StepList/StepDetails.tsx
  src/components/StepSeparator.tsx
  src/contexts/StepsContext.ts
  src/helpers/generator.test.ts
  src/helpers/generator.ts
  src/hooks/useStepsContext.test.ts
  src/hooks/useStepsContext.ts
  src/hooks/useSyntheticsTest.ts
Labels: enhancement

#183 ci: release automation for unsigned artifacts (stage 1)
  .ci/Jenkinsfile
  .ci/Makefile
  RELEASE.md
  package.json
Labels: Team:Automation

#178 fix: URL input expands for longer value
  src/components/Header/HeaderControls.tsx
  src/components/Header/UrlField.tsx
Labels: bug

#198 chore: Add update to `README.md` to explain undefined reference error
  README.md
Labels: documentation, chore

#207 fix: Make Test button disabled during recording/paused states
  src/components/Header/HeaderControls.tsx
Labels: bug

#206 fix: Header layout when paused
  src/components/Header/HeaderControls.tsx
Labels: bug

#208 fix: Reset default values when action/assertion edit view closes
  e2e/tests/assertionInfo.test.ts
  src/components/ActionElement/ActionElement.tsx
Labels: bug

#212 fix: use action.url instead of frameUrl in header
  e2e/tests/actionValues.test.ts
  src/components/ActionElement/HeadingText.tsx
Labels: bug

#219 chore: Bump EUI version
  package-lock.json
  package.json
Labels: chore

#218 fix: Disable record journey button when URL input is empty
  src/components/Header/HeaderControls.tsx
Labels: enhancement

#215 feat: Hide duration element for skipped step
  src/components/TestResult/ResultFlyoutItem.tsx
Labels: enhancement

#213 fix: Clear steps as part of `startOver` procedure
  src/App.tsx
  src/hooks/useRecordingContext.ts
Labels: bug

#209 chore: Simplify generator unit test
  src/helpers/generator.test.ts
  src/helpers/test/createAction.ts
Labels: chore

#217 feat: Update start over warning modal copy
  src/components/StartOverWarningModal.tsx
Labels: enhancement

#205 chore: convert electron js to ts
  .gitignore
  common/types.d.ts
  e2e/services/electron.ts
  e2e/setup/builder.js
  electron-builder.yml
  electron/config.ts
  electron/electron.ts
  electron/execution.ts
  electron/menu.ts
  nodemon.json
  package-lock.json
  package.json
  src/common/shared.ts
  src/common/types.ts
  src/components/ExportScriptFlyout/Flyout.tsx
  src/components/ExportScriptFlyout/Footer.tsx
  src/components/SaveCodeButton.tsx
  src/components/TestResult/ResultBody.tsx
  src/components/TestResult/ResultErrorBody.tsx
  src/components/TestResult/ResultFlyoutItem.tsx
  src/components/TestResult/TestResult.tsx
  src/components/TestResult/styles.tsx
  src/contexts/TestContext.ts
  src/helpers/resultReducer.ts
  src/hooks/useSyntheticsTest.ts
  tsconfig.base.json
  tsconfig.json
  tsconfig.node.json
Labels: chore

#223 ci: report test results
  .ci/Jenkinsfile
  .gitignore
  jest.e2e.config.js
  jest.unit.config.js
  package-lock.json
  package.json
Labels: Team:Automation

#226 feat: Add status indicator to assertion elements
  src/components/ActionElement/ActionElement.tsx
  src/components/ActionElement/Behavior.tsx
Labels: enhancement

#227 ci: refactor the docker build stage
  .ci/Jenkinsfile
  .ci/scripts/docker-build.sh
  .ci/scripts/docker-push.sh
  .ci/scripts/run-test-in-docker.sh
  .ci/scripts/run-test.sh
  e2e/Dockerfile.jenkins
Labels: Team:Automation

#231 chore: Move `createAction` test helpers to top level of repo
  common/helper/test/createAction.ts
  common/types.d.ts
  src/helpers/generator.test.ts
  src/helpers/test/index.ts
  src/hooks/useDragAndDrop.test.ts
  src/hooks/useDrop.test.ts
  src/hooks/useStepsContext/useStepsContext.test.ts
  tsconfig.base.json
  tsconfig.json
  tsconfig.node.json
Labels: chore

#233 fix: Error not showing in failed test result flyout
  electron/execution.ts
Labels: bug

#211 fix: Hoist page objects in generated code
  common/helper/test/createAction.ts
  electron/__snapshots__/syntheticsGenerator.test.ts.snap
  electron/execution.ts
  electron/syntheticsGenerator.test.ts
  electron/syntheticsGenerator.ts
  jest.unit.config.js
  package.json
Labels: bug
