Repository elastic/synthetics-recorder, pull requests merged in 2022-03, with the labels that each got.

#148 feat: Step divider manipulation
  src/contexts/StepsContext.ts
  src/helpers/test/defaults.ts
  src/hooks/useStepsContext.test.ts
  src/hooks/useStepsContext.ts
Labels: enhancement

#159 feat: Show all action titles in step containers for test result flyout
  e2e/tests/testResult.test.ts
  electron/execution.js
  src/App.tsx
  src/common/shared.test.ts
  src/common/types.ts
  src/components/TestResult/ResultBody.tsx
  src/components/TestResult/ResultErrorBody.tsx
  src/components/TestResult/ResultFlyoutItem.tsx
  src/components/TestResult/ResultTitle.tsx
  src/components/TestResult/styles.tsx
  src/helpers/resultReducer.test.ts
  src/hooks/useRecordingContext.ts
  src/hooks/useSyntheticsTest.ts
Labels: enhancement

#176 fix: Update EUI version and switch to Amsterdam
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/TestResult/ResultFlyoutItem.tsx
  src/components/TestResult/ResultTitle.tsx
  src/components/TestResult/styles.tsx
  src/contexts/StyledComponentsEuiProvider.tsx
Labels: bug

#177 chore: update deps and add `lint-staged`
  .husky/pre-commit
  demo-app/package.json
  package-lock.json
  package.json
  src/App.tsx
Labels: chore

#160 feat: Add tooltip to assertion element heading
  e2e/services/electron.ts
  e2e/tests/assertionInfo.test.ts
  src/common/shared.ts
  src/components/ActionElement/ActionElement.tsx
  src/components/Assertion/Assertion.tsx
  src/components/Assertion/AssertionInfo.tsx
Labels: enhancement

#179 fix: Make assertions expanded on init
  src/components/ActionElement/ActionElement.tsx
Labels: bug

#182 fix: Fill defect for `ControlButton`
  src/components/ControlButton.tsx
Labels: bug

#181 ci: release tag based (stage 1)
  .ci/Jenkinsfile
  .ci/Makefile
Labels: Team:Automation
